[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=13.0", "-C", "link-args=-undefined dynamic_lookup -ObjC"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=13.0"]